### ISSUE TITLE
Home work for John

### ISSUE THREAD

**Issue by johnmcgrath19** [holtzy/NbEpi#4]
Hi Yan, I tried to make some simple changes to the website, but was not sure how to PUSH to you. I hit the PULL REQUEST button, but I did not get a feeling it looked right. 
Issues in list format: 

- Do we need TEAM button...might have this elsewhere. 

- Twitter and Github buttons fine. The instragram one can be dropped. 

- I tried to update the text in the 3 column section..but could not see it in HTML...

- Lets call the next section Publications and Presentation. I like the way you have the content shown and the hyperlinks etc. I will explore how to use this soon. 

- Projects. Not sure the hover function...I would prefer the viewer see WHAT is linked to the boxes WITHOUT having to hover over it. We have have TEXT plus a figure...  I like the text you have in the red hover box. Ditto for the intro video...we might have these in a Youtube channel or vimeo. Then the Youtube link....we might just call this "Conference Videos"

- Can you insert the logos - as in the NB-COMO site? Esp. the funder. 
 
- Contact

 stuff is fine. 

- Drop the Map

- Final text - drop the instragram. 

 That should be enough for now :)
Cheers
John

**Comment by holtzy** [comment]
Hi John,
Your pull request worked fine. New text is online.

All the bullet points above to be made soon

**Comment by holtzy** [comment]
Hi John,

All the issues solved.

Feel free to send other feedbacks!
