### ISSUE TITLE
Suggestions for webpage

### ISSUE THREAD

**Issue by johnmcgrath19** [holtzy/NbEpi#7]
1. Don't forget to change the names of your Repos in order to take out 'vit D' or 'vitamin D' - relabelled JM project or something cryptic :)
2. nbepi home page. Can you expand the Menu list: 

- Publications

- Interactive data visualization webpages

- Slides/presentations

- Conference presentation videos
 
- Animations and educational material

- Code and GitHub links

3. Under the NBP logo, delete the twitter and github symbols...we will have more than one github link. But leave the twitter link to me at the bottom of the page. Insert hyperlink to the main AU NBP page
4. Next section (near to my photo)..I have adjusted the paragraph breaks. 

First Heading: Publications - can you insert this one https://www.ncbi.nlm.nih.gov/pubmed/29322163 ...not sure how best to display the reference - what do you recommend?? But, we want the URL to point to the PubMed link....and also have a link to the pdf ( I will upload here to this Issues Box). 
[Pragmatic Psychiatric Epidemiology—If You Can’t Count It, It Won’t Count.pdf](https://github.com/holtzy/NbEpi/files/2268500/Pragmatic.Psychiatric.Epidemiology.If.You.Can.t.Count.It.It.Won.t.Count.pdf)

I will add to this list once the papers are published. 

Next heading: Interactive data visualization webpages
 Comorbidity within mental disorders - Danish register study **what shall we do..have this title hyperlinked?? 
https://holtzyan.shinyapps.io/the-nb-como-project/

We can add to this...anything else to put here..your ICD code etc??

Next heading: Slides/presentations 
The pervasive nature of comorbidity within mental disorders: a comprehensive, nationwide cohort study **shall we have this entire title hyperlinked ??Your thoughts? Should the hyperlink go to a dropbox site or to the GitHub folder??

Next heading: Conference presentation videos
Youtube channel (URL link)**we will not subdivide the Youtube channel..it will be a repository for all future NBP conferences.... 

next heading: Animations and educational material
What is comorbidity? *insert hyperlink....the videos will be too big to upload on git hub??

next heading: Code and GitHub links

- Code for this publication "The pervasive nature of comorbidity within mental disorders: a comprehensive, nationwide cohort study"   **what do you think..hyperlink this to Oleguer specific Repo for this code?
- Code for interactive data viz site: **insert your GitHub for the COmo page?? 

5. Delete the hover feature. 
- Publications
* insert the NBP pattern 
![nbp red graphics](https://user-images.githubusercontent.com/23657684/43810252-ff383cd0-9af9-11e8-84d4-ba3ebdb4732f.jpg)

- Interactive data visualization webpages
**Yan - can you insert the Sankey plot here..maybe a version that is not TOO BUSY... 

- Slides/presentations
Maybe add text like "SIRS Conference Florence 2018. The pervasive nature of comorbidity within mental disorders: a comprehensive, nationwide cohort study"  make hyperlink?
**maybe use one of our painting...like this one...
![craig finn painting sz](https://user-images.githubusercontent.com/23657684/43810390-b9941216-9afa-11e8-959b-1c01e9cd11ea.jpg)

- Conference presentation videos
 Link to our Youtube  
Use this picture 
![nbp lecture theatre](https://user-images.githubusercontent.com/23657684/43810451-0e0d7134-9afb-11e8-8e34-6a689d5e7189.jpg)

- Animations and educational material

??What will we link to..not sure where the animations will go...could put them on the YouTube channel, but point to the specific URL?? 
Can you make a screen capture from the animation??

- Code and GitHub links
Use the GitHub logo as the picture maybe, and add a few links...

5. Then, at the end, can you include the logos? 
DNRF, AU, UQ, Harvard, the NBP logo

6. Can delete the GIThub contact, but leave twitter and my email. 

Hope that makes sense. 
Cheers
John

**Comment by holtzy** [comment]
Hi John,

I got the issue! will start working on it, result ASAP.

**Comment by holtzy** [comment]
Hi John,

Most of the issues are fixed, but not all.
